#!/usr/bin/env python3
"""Single-file copies of the Razorpay edge functions for the Supabase
dashboard editor, which deploys one file per function and cannot resolve
../_shared imports. Output: supabase/functions/dist/<name>.ts — paste each
into Dashboard → Edge Functions → <name> (JWT verification off)."""
import pathlib, re

root = pathlib.Path(__file__).resolve().parent.parent / 'supabase' / 'functions'
shared = (root / '_shared' / 'razorpay.ts').read_text()
out = root / 'dist'
out.mkdir(exist_ok=True)
for fn in ['razorpay-order', 'razorpay-verify', 'razorpay-webhook', 'delete-account', 'admin-delete-user', 'push-send']:
    src = (root / fn / 'index.ts').read_text()
    src = re.sub(r"^import \{[^}]*\} from '\.\./_shared/razorpay\.ts'\n", '', src, flags=re.M)
    assert '_shared' not in src, fn
    (out / f'{fn}.ts').write_text(f'// {fn} — generated by scripts/bundle-functions.py; edit the sources, not this.\n\n'
                                  + shared + '\n// ---- ' + fn + '\n' + src)
    print('wrote', out / f'{fn}.ts')
