"""Write supabase/catalogue-places.sql: the app's catalogue as server rows.

Saves, reviews and posts reference places(id), so every catalogue place must
exist on the server too. Rows carry name and position only (added_by null —
nobody owns them); photos and credits stay in the app's build. Re-run and
re-apply after scripts/build-catalogue.py changes the catalogue.

    python3 scripts/catalogue-sql.py
"""
import json

places = json.load(open('src/lib/catalogue.json'))
q = lambda s: "'" + str(s or '').replace("'", "''") + "'"
rows = ',\n'.join(
    f"  ({q(p['id'])}, {q(p['name'])}, {q(p.get('region'))}, {q(p.get('country'))}, {p['lat']}, {p['lng']}, {q(p.get('blurb'))})"
    for p in places)
sql = f"""-- Generated by scripts/catalogue-sql.py — {len(places)} catalogue places.
insert into places (id, name, region, country, lat, lng, blurb) values
{rows}
on conflict (id) do update set
  name = excluded.name, region = excluded.region, country = excluded.country,
  lat = excluded.lat, lng = excluded.lng, blurb = excluded.blurb
  where places.added_by is null;
"""
open('supabase/catalogue-places.sql', 'w').write(sql)
print(len(places), 'rows,', len(sql), 'bytes')
